#Spring service的属性
server:
  port: 9001
  servlet:
    session:
      timeout: 30m

# Spring的系列的属性
spring:
  #配置Spring服务的名称
  application:
    name: athena-coupon
  #配置Spring datebase的账户和连接
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.25.137:32081/athena_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      # 配置的Springcloud服务注册中心
      discovery:
        server-addr: 192.168.25.137:8848
      config:
        server-addr: 192.168.25.137:8848
  # 配置日期相关的格式的输出
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

# mybatis-plus的系列的属性
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #设置实体类的自增主键
  global-config:
    db-config:
      id-type: auto

# 日志数据输出
logging:
  level:
    com.zhuangxiaoyan.athena.coupon: debug
