#Spring service的属性
server:
  port: 14000
  servlet:
    session:
      timeout: 30m

# Spring的系列的属性
spring:
  # 配置Spring服务的名称
  application:
    name: athena-oss
  # Springcloud alibaba nacos注册中心
  cloud:
    nacos:
      # 配置的Springcloud服务注册中心
      discovery:
        server-addr: 192.168.25.137:30768

